# Generated by Django 4.0.4 on 2022-09-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_estabelecimento_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto'),
            preserve_default=False,
        ),
    ]
