# Generated by Django 4.0.4 on 2022-12-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_venda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
